### ISSUE TITLE
Fix Before 2.x Launch: Album videos are not playable

### ISSUE THREAD

**Issue by dsidious1** [mgp25/Instagram-API#1062]
After upload videos, covers and configure it with query 'media/configure_sidecar/' album in timeline has only covers without vids (without 'play' button).

Function "uploadVideoData" ignore parameter 'type'.

**Comment by dsidious1** [comment]
After upload videos, covers and configure it, album in timeline has only covers without vids.

Function "uploadVideoData" ignore parameter 'type'.

**Comment by SteveJobzniak** [comment]
> After upload videos, covers and configure it with query 'media/configure_sidecar/' album in timeline has only covers without vids (without 'play' button).

Okay, do you have ffmpeg on your system which is required for video uploads?

> Function "uploadVideoData" ignore parameter 'type'.

Intentional. It's just there to allow us to process things different IF we ever need to.

**Comment by dsidious1** [comment]
>>Okay, do you have ffmpeg on your system which is required for video uploads?

Yes.  I tested it in many ways - only covers in albums are published. Do you test this feature itself?

**Comment by SteveJobzniak** [comment]
@dsidious1 I don't know. @mgp25 did the testing of the album uploads. Perhaps it's true that the video files don't get assigned properly. We'll have to check when we have time. Thanks for reporting it if there's indeed a problem.

**Comment by dsidious1** [comment]
Thanks! Waiting for fix)

**Comment by mgp25** [comment]
@dsidious1 i detected the issue, ill soon send a fix

Regards

**Comment by dsidious1** [comment]
@mgp25 cool, thx! please, let me know here.

**Comment by SteveJobzniak** [comment]
@dsidious1 We will close the ticket when it is fixed, you will know then. ;)

**Comment by SteveJobzniak** [comment]
Okay so @mgp25 this is the last remaining bug that needs fixing.

Even after all our recent work, videos are not playable in albums. They are only uploaded as a thumbnail. I guess it's a configure() issue in its album handling. Good luck. 👍

**Comment by dsidious1** [comment]
>>I guess it's a configure() issue in its album handling.

@SteveJobzniak  Yes, I think so too.

**Comment by SteveJobzniak** [comment]
Update: It's taking some time to get the new app emulated and checking the proper parameters. Please be patient. It will be fixed as soon as possible. We want to get this done as much as you do. :-)

**Comment by mgp25** [comment]
Problem wasnt in the configure. Posting video to album is already fixed. We forgot to add a cookie value to the request while uploading chunks, once this is added we can close this issue and video to album will work.

I also added this few changes (although there are more to be added, but not strictly required at the moment) - https://github.com/mgp25/Instagram-API/commit/e79a5687acc7ae39e0fd38a47fc6e04bdd5b3aa2

**Comment by dsidious1** [comment]
@mgp25 I use your changes, but video album post still not working. During thumbnail upload IG returns: {"status": "fail", "message": "Server got a conflicting upload id"}. If I use different upload_id for vid and thumbnail then during configure() IG returns: {"status": "fail", "message": "Other media configure error: b'RjqdfiDWUA'"}

**Comment by mgp25** [comment]
@dsidious1 have you read what i have posted? **Posting video to album is ->almost<- fixed**, it needs some few changes, maybe this afternoon will be fixed

Regards

**Comment by dsidious1** [comment]
@mgp25 ok, sorry)

**Comment by mgp25** [comment]
@dsidious1 no problem, i'll let you know when its fixed

Regards

**Comment by mgp25** [comment]
@dsidious1 fixed. It will be pushed later today

Regards

**Comment by dsidious1** [comment]
What exactly was changed?
