### ISSUE TITLE
"Unknown Server Error" when configuring timeline photo

### ISSUE THREAD

**Issue by szokeptr** [mgp25/Instagram-API#2665]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

/////// CONFIG ///////
$username = 'REDACTED';
$password = 'REDACTED';
$debug = true;
$truncatedDebug = false;
//////////////////////

/////// MEDIA ////////
$photoFilename = 'tst.jpg';
$captionText = 'A and B and C';
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->setVerifySSL(false);
$ig->setProxy('http://127.0.0.1:8888');
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
    // The most basic upload command, if you're sure that your photo file is
    // valid on Instagram (that it fits all requirements), is the following:
    // $ig->timeline->uploadPhoto($photoFilename, ['caption' => $captionText]);

    // However, if you want to guarantee that the file is valid (correct format,
    // width, height and aspect ratio), then you can run it through our
    // automatic photo processing class. It is pretty fast, and only does any
    // work when the input file is invalid, so you may want to always use it.
    // You have nothing to worry about, since the class uses temporary files if
    // the input needs processing, and it never overwrites your original file.
    //
    // Also note that it has lots of options, so read its class documentation!
    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename);
    $ig->timeline->uploadPhoto($photo->getFile(), ['caption' => $captionText]);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

```

Error Log/var_dump:

```php

POST:  https://i.instagram.com/api/v1/upload/photo/
→ 876.36kB
← 200    71B
RESPONSE: {"upload_id": "384085791459759", "xsharing_nonces": {}, "status": "ok"}

POST:  https://i.instagram.com/api/v1/media/configure/?timezone_offset=0
DATA: signed_body=6b11bb2ba7f462cac1052d1efcdedb9fbb72a8fc4c1218907b15f71e61f315c3.{"device":{"manufacturer":"OnePlus","model":"ONEPLUS A3010","android_version":"24","android_release":"7.0"},"date_time_digitalized":"2019:05:17 10:41:26","_csrftoken":"TOKEN","media_folder":"Camera","source_type":"4","_uid":"USERID","_uuid":"UUID","edits":{"crop_original_size":[1017,1097],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":1017,"source_height":1097},"caption":"A and B and C","date_time_original":"2019:05:17 10:41:26","upload_id":"384085791459759"}&ig_sig_key_version=4
← 500    54B
RESPONSE: {"message": "Unknown Server Error.", "status": "fail"}
```

---

### Description of issues

I know this is a duplicate but the other issues were closed as invalid, without any answers.

The problem is very tricky, because sometimes the post is uploaded without issues, sometimes it fails when it tries to configure it.
There are files that never fail, and there are files that will only upload in 5-10% of the cases.

Let me know if you need more details.

Forgot to mention: I am using the latest code from `master` branch.

**Comment by davidenco** [comment]
Same issue here. Some posts are successful whereas others are not and fail with this stupid, vague error. Surely saying "something went wrong, but we have no idea what" would be better?!

**Comment by JRoy** [comment]
There is a fix in the pipeline for this, it will be released soon.

Regards.

**Comment by szokeptr** [comment]
@JRoy It would be great to know if this is a problem with the requests that are being sent because in that case, I would stop using this library until it's fixed to avoid getting flagged by Instagram.

**Comment by mgp25** [comment]
Hello,

I have already fixed this, it hasn't been released yet because I want to polish the code to avoid  pushing spaghetti code to the repo.

Regards

**Comment by JRoy** [comment]
@szokeptr it is a problem with the segmented media uploader not being selected properly. You should have no concerns other than media uploading with the API however

**Comment by szokeptr** [comment]
Isn't the segmented media uploader only used for videos? My issue is about a photo post. 
Or they started using the segmented uploader for photo posts too?

**Comment by mgp25** [comment]
Photos are used by segmented uploader too

**Comment by szokeptr** [comment]
@mgp25 could you please point me to the code where the segmented uploader is used in the current (`dev-master`) is used for photos? I might be missing something here, but as far as I can see it's either  `_uploadPhotoInOnePiece` or `_uploadResumablePhoto`.

**Comment by mgp25** [comment]
I will post some temporary fix, but I don't want people to use something that it is not 100% correct. That could cause other issues. You need to look at `_useResumablePhotoUploader` but I dont recommend you changing anything until a fix is done because there are many things that have changed.

**Comment by stek29** [comment]
For anyone else who ends up here -- temporary fix is to make `Internal::_useResumablePhotoUploader` always return true.

**Comment by aliazizi** [comment]
@mgp25 this issue fixed yet?

**Comment by aliazizi** [comment]
@JRoy you should keep issue open until release fix, Closed issue refer to solved issue and this issue is not solved!

**Comment by usamaejaz** [comment]
Could we get a temporary fix (or at least details about that)?

**Comment by JRoy** [comment]
@usamaejaz look above

**Comment by usamaejaz** [comment]
@JRoy I have tried a fix. 

Before uploading the (single) photo,

```
$origExperiments = $ig->experiments;
```


```
if($ig->isExperimentEnabled('ig_android_photo_fbupload_universe', 'is_enabled_fbupload_photo')) {
    $ig->experiments['ig_android_photo_fbupload_universe']['is_enabled_fbupload_photo'] = 'false';
}
```

After the upload,

```
$ig->experiments = $origExperiments;
```

This way, the image is uploaded without using resumable photo uploader. Is it something that I am still missing?

**Comment by JRoy** [comment]
@usamaejaz I do not want to confirm an incomplete fix but you'll want to look at mgp25's message above until we release a fix

**Comment by genisaretskiy** [comment]
Hello, is this issue already fixed?

**Comment by aliazizi** [comment]
@genisaretskiy no, we are still waiting

**Comment by maxweber** [comment]
Has a solution been found? This issue causes a lot of failed story posts. Thank you very much in advance.

**Comment by sergeykomlev** [comment]
This is fixed yet or not?

**Comment by JRoy** [comment]
We are working on a permanent fix, the app still doesn't always use the resumable photo editor so we want to make sure we are emulating the app properly. 

To temporarily get around this, you'll need to make sure you're using `_uploadResumablePhoto` all of the time in the Internal class. No support will be given for the exact implementation and no support will be given if anything goes wrong.

We hope to have a more permanent fix soon!

**Comment by usamaejaz** [comment]
The "Unknown server error." is still appearing even when we are always using _uploadResumablePhoto

**Comment by capslog** [comment]
I have similar problem, but the image is sended and caption not sended

**Comment by usamaejaz** [comment]
> I have similar problem, but the image is sended and caption not sended

@capslog are you sure? that usually happens when you add a lot of hashtags to the caption.

**Comment by aliazizi** [comment]
I have same problem, the image is sended and caption not sended

**Comment by capslog** [comment]
> > I have similar problem, but the image is sended and caption not sended
> 
> @capslog are you sure? that usually happens when you add a lot of hashtags to the caption.

i aways send hashtags and a few days ago stoped...

**Comment by novinhubcom** [comment]
It's about 2 month, i'm sorry for ask again, can we have at least temporary fix? I can't use this library for this 2 months

**Comment by aliazizi** [comment]
It's about 2 month, i'm sorry for ask again, can we have at least temporary fix? I can't use this library for this 2 months

**Comment by mariefs** [comment]
Yah, the same here, almost 2 months my posts go up without caption
